name: Code Review1

permissions:
  contents: read
  pull-requests: write

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  pull_request_review_comment:
    types: [created]

concurrency:
  group: ${{ github.repository }}-${{ github.event.number || github.head_ref ||
    github.sha }}-${{ github.workflow }}-${{ github.event_name ==
    'pull_request_review_comment' && 'pr_comment' || 'pr' }}
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: AI-based PR Reviewer & Summarizer with Mistral 8x7B Chat Capabilities
        uses: Onigam/ai-mistral-pr-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          OPENAI_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        with:
          debug: false
          openai_base_url: "https://codestral.mistral.ai/v1"
          openai_light_model: "mistral-tiny"
          openai_heavy_model: "mistral-small"
